/**
 * Shared Tags - Common tagging utilities
 * Generated by EZ Agents Infrastructure Service
 */

export const commonTags = {
  CostCenter: "engineering",
  Project: "ez-agents",
  Owner: "platform-team",
  ManagedBy: "pulumi"
};

export function mergeTags(baseTags: Record<string, string>, additionalTags?: Record<string, string>) {
  return {
    ...commonTags,
    ...baseTags,
    ...additionalTags
  };
}

export function validateTags(tags: Record<string, string>): boolean {
  const requiredKeys = ['CostCenter', 'Project', 'Owner', 'Environment', 'ManagedBy'];
  return requiredKeys.every(key => key in tags);
}
