/**
 * Auto-scaling Module - Compute scaling configuration
 * Generated by EZ Agents Infrastructure Service
 * 
 * Uses target tracking with CPU threshold of 70%
 */

import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const commonTags = {
  CostCenter: "engineering",
  Project: "ez-agents",
  Owner: "platform-team",
  ManagedBy: "pulumi"
};

export interface AutoScalingConfig {
  minCapacity: number;
  maxCapacity: number;
  desiredCapacity?: number;
  instanceType: string;
  cpuThreshold?: number; // Target CPU utilization (default: 70%)
  environment: string;
}

export function createAutoScalingGroup(
  name: string,
  config: AutoScalingConfig,
  vpcId: pulumi.Input<string>,
  subnets: pulumi.Input<string>[],
  tags?: Record<string, string>
) {
  
  const launchConfig = new aws.ec2.LaunchConfiguration(`${name}-launch`, {
    instanceType: config.instanceType,
    // Add AMI, security group, user data as needed
    tags: [
      { key: "Name", value: name, propagateAtLaunch: true },
      { key: "Environment", value: config.environment, propagateAtLaunch: true },
      ...Object.entries({ ...commonTags, ...tags }).map(([key, value]) => ({
        key,
        value,
        propagateAtLaunch: true
      }))
    ]
  });

  const asg = new aws.autoscaling.Group(name, {
    minSize: config.minCapacity,
    maxSize: config.maxCapacity,
    desiredCapacity: config.desiredCapacity || config.minCapacity,
    launchConfiguration: launchConfig.name,
    vpcZoneIdentifiers: subnets,
    targetGroupArn: config.targetGroupArn,
    tags: [
      { key: "Name", value: name, propagateAtLaunch: true },
      { key: "Environment", value: config.environment, propagateAtLaunch: true },
      ...Object.entries({ ...commonTags, ...tags }).map(([key, value]) => ({
        key,
        value,
        propagateAtLaunch: true
      }))
    ]
  });

  // Target tracking scaling policy with 70% CPU threshold
  const scalingPolicy = new aws.autoscaling.Policy(`${name}-scaling`, {
    autoscalingGroupName: asg.name,
    policyType: "TargetTrackingScaling",
    targetTrackingConfiguration: {
      predefinedMetricSpecification: {
        predefinedMetricType: "ASGAverageCPUUtilization"
      },
      targetValue: config.cpuThreshold || 70
    }
  });

  return { asg, launchConfig, scalingPolicy };
  
}
