/**
 * CDN Module - CloudFront distribution configuration
 * Generated by EZ Agents Infrastructure Service
 */

import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const commonTags = {
  CostCenter: "engineering",
  Project: "ez-agents",
  Owner: "platform-team",
  ManagedBy: "pulumi"
};

export interface CdnConfig {
  originDomain: string;
  priceClass?: 'PriceClass_100' | 'PriceClass_200' | 'PriceClass_All';
  environment: string;
}

export function createCdnDistribution(name: string, config: CdnConfig, tags?: Record<string, string>) {
  
  const distribution = new aws.cloudfront.Distribution(name, {
    enabled: true,
    priceClass: config.priceClass || 'PriceClass_100',
    origins: [{
      originId: config.originDomain,
      domainName: config.originDomain,
      customOriginConfig: {
        httpPort: 80,
        httpsPort: 443,
        originProtocolPolicy: "https-only", // HTTPS redirect
        originSslProtocols: ["TLSv1.2"]
      }
    }],
    defaultCacheBehavior: {
      targetOriginId: config.originDomain,
      viewerProtocolPolicy: "redirect-to-https", // HTTPS redirect
      allowedMethods: ["GET", "HEAD", "OPTIONS", "PUT", "POST", "PATCH", "DELETE"],
      cachedMethods: ["GET", "HEAD"],
      forwardedValues: {
        queryString: false,
        cookies: { forward: "none" }
      },
      minTtl: 0,
      defaultTtl: 3600,
      maxTtl: 86400
    },
    restrictions: {
      geoRestriction: {
        restrictionType: "none",
        locations: []
      }
    },
    viewerCertificate: {
      cloudfrontDefaultCertificate: true
    },
    tags: {
      Name: name,
      Environment: config.environment,
      ...commonTags,
      ...tags
    }
  });

  return distribution;
  
}
