/**
 * Load Balancer Module - ALB/NLB configuration
 * Generated by EZ Agents Infrastructure Service
 */

import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const commonTags = {
  CostCenter: "engineering",
  Project: "ez-agents",
  Owner: "platform-team",
  ManagedBy: "pulumi"
};

export interface LoadBalancerConfig {
  type: 'application' | 'network'; // ALB or NLB
  internal?: boolean;
  subnets: pulumi.Input<string>[];
  environment: string;
}

export function createLoadBalancer(name: string, config: LoadBalancerConfig, tags?: Record<string, string>) {
  
  const lb = new aws.lb.LoadBalancer(name, {
    internal: config.internal || false,
    loadBalancerType: config.type === 'application' ? 'application' : 'network',
    subnets: config.subnets,
    enableDeletionProtection: config.environment === 'prod',
    tags: {
      Name: name,
      Type: config.type === 'application' ? 'ALB' : 'NLB',
      Environment: config.environment,
      ...commonTags,
      ...tags
    }
  });

  // HTTPS Listener for ALB
  let httpsListener: aws.lb.Listener | undefined;
  if (config.type === 'application') {
    httpsListener = new aws.lb.Listener(`${name}-https`, {
      loadBalancerArn: lb.arn,
      port: 443,
      protocol: "HTTPS",
      // Add certificate ARN and SSL policy as needed
      defaultActions: [{
        type: "fixed-response",
        fixedResponse: {
          contentType: "text/plain",
          statusCode: "200",
          messageBody: "OK"
        }
      }]
    });
  }

  return { lb, httpsListener };
  
}
