/**
 * VPC Module - Network infrastructure
 * Generated by EZ Agents Infrastructure Service
 */

import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

// Mandatory tags for all resources
const commonTags = {
  CostCenter: "engineering",
  Project: "ez-agents",
  Owner: "platform-team",
  ManagedBy: "pulumi"
};

// VPC Configuration
export interface VpcConfig {
  cidrBlock: string;
  enableDnsHostnames: boolean;
  enableDnsSupport: boolean;
  environment: string;
}

export function createVpc(name: string, config: VpcConfig, tags?: Record<string, string>) {
  
  const vpc = new aws.ec2.Vpc(name, {
    cidrBlock: config.cidrBlock,
    enableDnsHostnames: config.enableDnsHostnames,
    enableDnsSupport: config.enableDnsSupport,
    tags: {
      Name: name,
      Environment: config.environment,
      ...commonTags,
      ...tags
    }
  });

  return vpc;
  
}

// Subnet configuration
export interface SubnetConfig {
  vpcId: pulumi.Input<string>;
  cidrBlock: string;
  availabilityZone: string;
  type: 'public' | 'private';
}

export function createSubnet(name: string, config: SubnetConfig, tags?: Record<string, string>) {
  
  const subnet = new aws.ec2.Subnet(name, {
    vpcId: config.vpcId,
    cidrBlock: config.cidrBlock,
    availabilityZone: config.availabilityZone,
    mapPublicIpOnLaunch: config.type === 'public',
    tags: {
      Name: name,
      Type: config.type,
      Environment: config.type === 'public' ? 'public' : 'private',
      ...commonTags,
      ...tags
    }
  });

  return subnet;
  
}
