/**
 * RDS Module - Database infrastructure
 * Generated by EZ Agents Infrastructure Service
 */

import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const commonTags = {
  CostCenter: "engineering",
  Project: "ez-agents",
  Owner: "platform-team",
  ManagedBy: "pulumi"
};

export interface RdsConfig {
  instanceClass: string;
  engine: string;
  engineVersion: string;
  allocatedStorage: number;
  multiAz: boolean;
  backupRetentionPeriod: number;
  environment: string;
}

export function createRdsInstance(
  name: string,
  config: RdsConfig,
  subnetIds: pulumi.Input<string>[],
  vpcId: pulumi.Input<string>,
  tags?: Record<string, string>
) {
  
  // Subnet group for RDS
  const subnetGroup = new aws.rds.SubnetGroup(`${name}-subnet-group`, {
    subnetIds,
    tags: {
      Name: `${name}-subnets`,
      Environment: config.environment,
      ...commonTags,
      ...tags
    }
  });

  // Security group for RDS
  const securityGroup = new aws.ec2.SecurityGroup(`${name}-sg`, {
    vpcId,
    ingress: [{
      protocol: "tcp",
      fromPort: 5432, // PostgreSQL default
      toPort: 5432,
      cidrBlocks: ["10.0.0.0/8"] // Internal VPC only
    }],
    egress: [{
      protocol: "-1",
      fromPort: 0,
      toPort: 0,
      cidrBlocks: ["0.0.0.0/0"]
    }],
    tags: {
      Name: name,
      Environment: config.environment,
      ...commonTags,
      ...tags
    }
  });

  // RDS Instance
  const instance = new aws.rds.Instance(name, {
    instanceClass: config.instanceClass,
    engine: config.engine,
    engineVersion: config.engineVersion,
    allocatedStorage: config.allocatedStorage,
    storageType: "gp3",
    multiAz: config.multiAz,
    backupRetentionPeriod: config.backupRetentionPeriod,
    dbSubnetGroupName: subnetGroup.name,
    vpcSecurityGroupIds: [securityGroup.id],
    skipFinalSnapshot: config.environment !== 'prod',
    deletionProtection: config.environment === 'prod',
    tags: {
      Name: name,
      Environment: config.environment,
      ...commonTags,
      ...tags
    }
  });

  return { instance, subnetGroup, securityGroup };
  
}
